= Knative Client
include::_attributes.adoc[]
:experimental:
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

https://github.com/knative/client[Knative Client] is the command line utility aimed at enhancing the developer experience when doing Knative Serving and Eventing tasks.

At the end of this chapter you will be able to :

* Install Knative Client 
* Create, update, list and delete Knative service
* Create, update, list and delete Knative service revisions
* List Knative service routes

[#kn-install]
== Install

Download the https://github.com/knative/client/releases/tag/knative-{kn-client-version}[{kn-client-version}^] Knative Client and add it to your `PATH`.

Verify installation by running the command:

[#kn-verify-install]
[.console-input]
[source,bash]
----
kn version
----

The above command will return a response like 

[source,text,subs="macros+,+attributes"]
[.console-output]
----
Version:      {kn-client-version}
Build Date:   2023-07-27T06:51:41Z
Git Revision: b7508e67
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving {kn-client-version})
* Eventing
  - sources.knative.dev/v1 (knative-eventing {kn-client-version})
  - eventing.knative.dev/v1 (knative-eventing {kn-client-version})
----

[#kn-ksvc]
== Knative Service Commands

[#kn-create-ksvc]
=== Create Service

To create the `greeter` service using `kn` run the following command:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service create greeter \
  --image {greeter-image}
----

A successful create of the `greeter` service should show a response like 

[.console-output]
[source,bash,subs="+attributes"]
----
Creating service 'greeter' in namespace 'knativetutorial':

  0.033s The Route is still working to reflect the latest desired specification.
  0.067s ...
  0.104s Configuration "greeter" is waiting for a Revision to become ready.
 13.195s ...
 13.210s Ingress has not yet been reconciled.
 13.299s Waiting for load balancer to be ready
 13.483s Ready to serve.

Service 'greeter' created to latest revision 'greeter-00001' is available at URL:
http://greeter.{tutorial-namespace}.{minikube-nip-io}
----
NB: on OpenShift the URL will be similar to: https://greeter-knativetutorial.apps.example.com

[#kn-list-services]
=== List Knative Services

You can list the created services using the command:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service list
----

[.console-output]
[source,text,subs="+quotes,+attributes"]
----
NAME      #URL#                                                   LATEST            AGE   CONDITIONS   READY   REASON
greeter   #http://greeter.knativetutorial.192.168.64.13.nip.io#  greeter-sxnzq-1   10m   3 OK / 3     True
----

=== Invoke Service
ifndef::workshop[]
--
include::serving:partial$invoke-service.adoc[tags=**;!workshop-call;!workshop-call-params]
--
endif::[]

[IMPORTANT]
====
For all the examples in the tutorial we have configured the xref:setup:minikube.adoc#configure-ingress-to-gateway[Ingress Controller and domain], which will use the domain suffix format like `**<service-name>.<namespace>.<minikube ip>.nip.io**`.

If you have not using the Ingress controller configuration then the service has to be invoked like `http $IP_ADDRESS 'Host:greeter.knativetutorial.example.com'`, you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative Routes and uses the following format: `**<service-name>.<namespace>.<domain-suffix>**`.
====

[#kn-update-ksvc]
=== Update Knative Service

To create a new revision using `kn` is as easy as running another command.

In previous chapter we deployed a new revision of Knative service by adding an environment variable. Lets try do the same thing with `kn` to trigger a new deployment:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service update greeter --env "MESSAGE_PREFIX=Namaste"
----

[.console-output]
[source,bash,subs="+macros,attributes+"]
----
Updating Service 'greeter' in namespace 'knativetutorial':

  2.737s Traffic is not yet migrated to the latest revision.
  2.762s Ingress has not yet been reconciled.
  2.785s Waiting for load balancer to be ready
  2.961s Ready to serve.

Service 'greeter' updated to latest revision 'greeter-00002' is available at URL:
http://greeter.{tutorial-namespace}.{minikube-nip-io}
----

Now <<kn-invoke-service,Invoking the service>> will return me a response like:

[.console-output]
[source,bash,subs="+macros,attributes+"]
----
Namaste  greeter => '9861675f8845' : 1
----

[#kn-desc-ksvc]
=== Describe Knative Service

Sometime you wish you get the YAML of the Knative service to build a new service or to compare with with another service. `kn` makes it super easy for you to get the YAML:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service describe greeter 
----

The describe should show you a short summary of your service : 

[.console-output]
[source,subs="+macros,attributes+"]
----
Name:       greeter
Namespace:  knativetutorial
Age:        13m
URL:        http://greeter.{tutorial-namespace}.{minikube-nip-io}

Revisions:  
  100%  @latest (greeter-00002) [2] (1m)
        Image:     quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)
        Replicas:  0/0

Conditions:  
  OK TYPE                   AGE REASON
  ++ Ready                   1m
  ++ ConfigurationsReady     1m
  ++ RoutesReady             1m
----

==== Describe with verbosity

To list all the revisions as part of the `describe` command use:

[.console-input]
[source,subs="+macros,attributes+"]
----
kn service describe greeter -v
----
[.console-output]
[source,text,subs="+quotes,+macros,attributes+"]
----
Name:         greeter
Namespace:    knativetutorial
Annotations:  serving.knative.dev/creator=admin
              serving.knative.dev/lastModifier=admin
Age:          14m
URL:          http://greeter.{tutorial-namespace}.{minikube-nip-io}
Cluster:      http://greeter.{tutorial-namespace}.svc.cluster.local

Revisions:
  100%  @latest (greeter-00002) [2] (3m)
        Image:     quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)
        Replicas:  0/0
        Env:       MESSAGE_PREFIX=Namaste
     +  greeter-00001 [1] (15m)
        Image:     quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)
        Replicas:  0/0

Conditions:
  OK TYPE                   AGE REASON
  ++ Ready                   3m
  ++ ConfigurationsReady     3m
  ++ RoutesReady             3m
----

==== Get Service URL

To get the Knative service url use `describe` with `-o url` option:

[.console-input]
[source,bash,subs="attributes+"]
----
kn service describe greeter -o url
----

[.console-output]
[source,bash,subs="attributes+"]
----
http://greeter.{tutorial-namespace}.{minikube-nip-io}
----

[#kn-revisions]
== Knative Revision Commands

The `kn` revision commands are used to interact with revision(s) of Knative service.

[#kn-revisions-list]
=== List Revisions

You can list the available revisions of a Knative service using:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision list
----

[.console-output]
[source,bash]
----
NAME            SERVICE   TRAFFIC   TAGS   GENERATION   AGE     CONDITIONS   READY   REASON
greeter-00002   greeter   100%             2            3m37s   3 OK / 4     True    
greeter-00001   greeter                    1            16m     3 OK / 4     True
----

[#kn-revisions-desc]
=== Describe Revision

To get the details about a specific revision you can use the command:

[#run-kn-desc-rev]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision describe greeter-00001
----

[.console-output]
[source,bash]
----
Name:       greeter-00001
Namespace:  knativetutorial
Age:        19m
Image:      quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)
Replicas:   0/0
Service:    greeter

Conditions:
  OK TYPE                  AGE REASON
  ++ Ready                 18m
  ++ ContainerHealthy      18m
  ++ ResourcesAvailable    18m
   I Active                 6m NoTraffic
----

[#kn-revisions-delete]
=== Delete Revision

To delete a specific revision you can use the command:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision delete greeter-00001
----

[.console-output]
[source,bash]
----
Revision 'greeter-00001' deleted in namespace 'knativetutorial'.
----

[#kn-routes]
== Knative Route Commands

The `kn` revision commands are used to interact with route(s) of Knative service.

[#kn-routes-list]
=== List Routes

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn route list
----

[.console-output]
[source,bash,subs="+macros,attributes+"]
----
NAME      URL                                                  READY
greeter   http://greeter.{tutorial-namespace}.{minikube-nip-io}   True
----

[#kn-cleanup]
== Delete Knative Service

You can also use `kn` to delete the service that were created, to delete the service named `greeter` run the following command:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service delete greeter
----

[source,bash]
[.console-output]
----
Service 'greeter' successfully deleted in namespace 'knativetutorial'.
----

<<kn-list-services,Listing services>> you will notice that the `greeter` service no longer exists.
